### ISSUE TITLE
Example code for legends breaks in IE11

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/charts#44] opened 2018-05-08 13:49 UTC
The [example code](https://github.com/mendixlabs/charts/blob/master/AdvancedCheatSheet.md#bottom) to show the legend below the graph fails in IE11. 
`{
  "showlegend": true,
  "legend": {
    "orientation": "h",
    "y": "auto"
  }
}`

Firefox (expected result):
![image](https://user-images.githubusercontent.com/1491873/39760798-9e011ca4-52d6-11e8-83e0-a1448eb8754a.png)

IE11:
![image](https://user-images.githubusercontent.com/1491873/39760781-8fd46d02-52d6-11e8-8f14-31aeb3246a2a.png)

Inspection in IE11 learns us that the SVG is higher than the containing element:
![image](https://user-images.githubusercontent.com/1491873/39760945-10d08cec-52d7-11e8-8dcf-44eb1a2496cb.png)

Setup in Mendix:
- Layout grid
- Row with 4 columns (3;3;3;3) each containing a Chart
- Row with 1 column (12) containing a datagrid

**Comment by Andries-Smit** [comment] 2018-05-09 07:46
Thank you Jelle for reporting the issue. We will investigate, however if the issue is caused by the plotly library it is probably hard for us to fix.

**Comment by edwinmp** [comment] 2018-05-17 06:45
Hi Jelle, I've implemented a fix that should be available in the next release. You can find a pre-release version [here](https://github.com/FlockOfBirds/charts/releases/tag/v1.2.1-beta). You can test with it and let me know if it fixes the problem.

**Comment by JelleDekker** [comment] 2018-05-28 07:33
Check, seems to be working fine now. Thanks!

**Comment by Andries-Smit** [comment] 2018-06-01 06:07
Solution to the issue is released into the app store https://appstore.home.mendix.com/link/app/105695/ version 1.2.1

**Closed by Andries-Smit** 2018-06-01 06:07 UTC
